### ISSUE TITLE
meta duplikate

### ISSUE THREAD

**Issue by HamburgerJungeJr** [dcngmbh/moox_core#35]
Ich habe gerade das Update auf moox_core 0.9.56 installiert und bekomme nun den content aller meta-Tags ausgegeben.

Im Quelltext sieht das so aus:
&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"&ggt;width=device-width, initial-scale=1.0, user-scalable=no&lt;/meta&gt;

Wie kann ich das beheben?

**Comment by jakub-czyz** [comment]
Ist ein Problem von VHS.
Entweder VHS eine Version downgraden oder den Patch anwenden:
https://github.com/FluidTYPO3/vhs/issues/790

**Comment by HamburgerJungeJr** [comment]
Habe den Patch angewendet und nun funktioniert alles wieder.
Danke!
