### ISSUE TITLE
Yag NivoSlider Bildgröße fehlerhaft

### ISSUE THREAD

**Issue by HamburgerJungeJr** [dcngmbh/moox_core#36]
Mit dem neuen Update 0.9.56 gibt es bei mir den Fehler, dass die Bilder der YAG-Gallery die Größe 0px x 0px erhalten. Mit der Version 0.9.9 funktioniert noch alles.

**Comment by jakub-czyz** [comment]
In der Version 0.9.9 war jQuery noch im head eingebunden, jetzt im footer aus Performance Gründen. Entweder man könnte das moox_core patchen über Typoscript oder man sorgt dafür dass YAG NivoSlider nach jQuery im footer geladen wird.

HTH Jakub

**Comment by HamburgerJungeJr** [comment]
Hast du einen Tipp für mich, wie ich YAG nach jQuery laden kann?

**Comment by adrolli** [comment]
Ungeprüft und etwas älter: http://typo3.toaster-schwerin.de/typo3_english/2012_03/msg00036.html

**Comment by HamburgerJungeJr** [comment]
Ich habe es jetzt zwar geschafft, dass jQuery vor den YAG-Importen steht, allerdings ist es auch noch danach.

&lt;script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" type="text/javascript"&gt;&lt;/script&gt;
&lt;script src="typo3conf/ext/yag_themepack_jquery/Resources/Public/GallerySource/NivoSlider/jquery.nivo.slider.pack.js?1426444589" type="text/javascript"&gt;&lt;/script&gt;
&lt;script type="text/javascript"&gt;
/*&lt;![CDATA[*/
/*nivoSlider-c64*/

				$(function() {
					  jQuery("#nivoSlider-c64").nivoSlider({"effect":"fade","slices":15,"boxCols":8,"boxRows":4,"animSpeed":500,"pauseTime":3000,"startSlide":0,"directionNav":true,"directionNavHide":true,"controlNav":true,"controlNavThumbs":true,"keyboardNav":true,"pauseOnHover":true,"manualAdvance":false,"captionOpacity":0.8,"randomStart":false,"controlNavThumbsFromRel":true});
				 });
			

/*]]&gt;*/
&lt;/script&gt;

&lt;script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="typo3temp/vhs-assets-6ee1a131700b1b9db38e57e1ce4ad367.js?1426670969"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="typo3temp/vhs-assets-047fb479a7bd732b3c3c300785df5b8e.js?1426670969"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="typo3temp/vhs-assets-1a58cdb37a1560b50bec5e05c95e9f56.js?1426670969"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="typo3temp/vhs-assets-0e01ec3502e0f09445bca028ed4db7f3.js?1426670969"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="typo3temp/vhs-assets-af9f712ee98b23136e4fdec2b7a90086.js?1426670969"&gt;&lt;/script&gt;

**Comment by jakub-czyz** [comment]
Jetzt hast du jQuery zweimal drin, das ist nicht in Ordnung. Versuche einfach mal folgendes in dein Typoscript Setup einzufügen:

plugin.tx_vhs.settings.asset{
	jquery {
		path = //ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js
		external = 1
		group = cdn
		standalone = 1
		movable = 0
		type = js
	}
} 

Somit überschreibst du die Einbindung von jQuery in der Extension moox_core und jQuery wird im head statt im foot eingebunden. So ist das auch in der Version 0.9.9 gewesen.

**Comment by HamburgerJungeJr** [comment]
Das hat schon einmal eine Verbesserung gebracht. Die Lösung des Problems liegt aber anscheinend in der jQuery-Version. Mit 1.8.3 funktioniert alles, mit 1.11.2  nicht.

**Comment by jakub-czyz** [comment]
Dann sollte das mit dieser Anpassung funktionieren:

plugin.tx_vhs.settings.asset{
jquery {
path = //ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js
external = 1
group = cdn
standalone = 1
movable = 0
type = js
}
}

Allerdings weiß ich nicht wie die andere Scripte auf deiner Webseite auf die Ältere jQuery Version reagieren. 

Sonst musst du .live() mit .on() Funktion in der YAG Extension austauschen.

**Comment by HamburgerJungeJr** [comment]
In der Version 3.2 auf GitHub wurde das Problem schon behoben.
Die Einbindung von jQuery mache ich nun so:
page.includeJSFooter{
  file1 = //ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js
  file1.external = 1
  file2 = //ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js
  file2.external = 1
  file3 = fileadmin/templates/nivoSlider.js /*die neue nivoslider.js*/
}
plugin.tx_vhs.settings.asset{
  jquery >
  jqueryuid >
}
