### ISSUE TITLE
moox_news ProductViewhelper

### ISSUE THREAD

**Issue by HamburgerJungeJr** [dcngmbh/moox_core#37]
Ich bekomme nun auch die Fehlermeldung 
Could not analyse class:Tx_Vhs_ViewHelpers_Math_ProductViewHelper maybe not loaded or no autoloader?

Sobald ich im backend unter "MOOX" die News aufrufen will.

**Comment by adrolli** [comment]
Urgh, kannst Du bitte mal die Ext-Versionen (evtl. als Screenshot) checken ... also VHS, Flux und Co. Die Problematik kennen wir nämlich noch nicht. 

Da wir momentan etwas hinterherhinken, was die aktuellen TER-Versionen betrifft (wir müssen uns leider grad auf einige weitere Extensions wie Shop und Payment konzentrieren und Core und News auf dem alten Versionsstand belassen), wird hier wohl auch schon eine der FluidTypo-Extensions zu "neu" sein.

**Comment by HamburgerJungeJr** [comment]
![ext1](https://cloud.githubusercontent.com/assets/11501266/6737892/da878f2c-ce6e-11e4-891b-ed408541ba25.PNG)
![ext2](https://cloud.githubusercontent.com/assets/11501266/6737893/daa2e9a2-ce6e-11e4-9e6a-aa92cc74fcc0.PNG)

**Comment by adrolli** [comment]
Da gibt es 2 mögliche Probleme:
- TYPO3 6.2.0 ist zu buggy, erst ab 6.2.7 haben wir (auch Fluid-seitig) Stabilität
- VHS läuft bei uns auf den Produktiv-Plattformen noch in 2.2.0, News ist mit 2.3.1 evtl. noch nicht zu 100% in-sync was die Viewhelper betrifft.

**Comment by adrolli** [comment]
Ah Nachtrag ... screen von einer stabilen Live-Plattform:

![stable](https://cloud.githubusercontent.com/assets/986701/6738164/6d45f9ce-ce70-11e4-98ba-f95bedaacfa0.jpg)

**Comment by HamburgerJungeJr** [comment]
Typo3 habe ich auch in der Version 6.2.11 installiert.
Der Downgrade auf vhs 2.2.0 hat geholfen.

**Comment by adrolli** [comment]
Ah, super. Danke fürs Feedback.

**Comment by HamburgerJungeJr** [comment]
Die fluidupdates sorgen allerdings für ein Fehler 500.

**Comment by adrolli** [comment]
Eigenartig, läuft auf vielen Plattformen bei uns. 

Grundsätzlich ist nach diesen Updates ein Full-Cache-Clear (am besten aus dem Installtool) sinnvoll.

Wenn das nicht hilft, ist ein 500er eine schlechte Grundlage für eine Problemanalyse ;-) die Plattform auf DEV stellen und es werden Fluid-Fehlerseiten sichtbar, die informativer sind.

Im schlimmsten Fall auf die alten Versionen zurück. Wir werden die Kompatibilität sicherlich in den nächsten Wochen aufholen und die von Dir verwendeten Versionen sind auch bereits stabil.

**Comment by HamburgerJungeJr** [comment]
Der Fehler kommt raus:
Fatal error: Declaration of DCNGmbH\MooxCore\Provider\CoreContentProvider::postProcessRecord() must be compatible with FluidTYPO3\Flux\Provider\ProviderInterface::postProcessRecord($operation, $id, array &$row, TYPO3\CMS\Core\DataHandling\DataHandler $reference, array $removals = Array) in /var/www/html/ackellinghusen/typo3conf/ext/moox_core/Classes/Provider/CoreContentProvider.php on line 46

**Comment by adrolli** [comment]
Hmm, kann ich bei uns auf die Schnelle nicht nachvollziehen. Auch wenn es eigentlich mit Flux 7.2.0 laufen sollte ... Flux-Dowgrade hilft?

**Comment by HamburgerJungeJr** [comment]
Wenn ich alle Fluid Updates deinstalliere funktioniert alles.

**Comment by HamburgerJungeJr** [comment]
Wenn ich die Datei, anpasse, wie es die Fehlermeldung fordert, bekomme ich eine neue:
Fatal error: Call to a member function getConfiguration() on a non-object in /var/www/html/ackellinghusen/typo3conf/ext/moox_core/Classes/Provider/CoreContentProvider.php on line 131

**Comment by mchenzi** [comment]
Hallo 
Habe das gleiche Problem. 


Fatal error: Declaration of DCNGmbH\MooxCore\Provider\CoreContentProvider::postProcessRecord() must be compatible with FluidTYPO3\Flux\Provider\ProviderInterface::postProcessRecord($operation, $id, array &$row, TYPO3\CMS\Core\DataHandling\DataHandler $reference, array $removals = Array) in /htdocs/domain/typo3conf/ext/moox_core/Classes/Provider/CoreContentProvider.php on line 46

es läuft 

typo3 6.2.11
und ansonsten die latest moox aber bei vhs version 2.2.0

Wenn ich im Backend eine seite anlegen will kommt der fehler. Kann also nix machen

**Comment by papckoff** [comment]
Hi.
typo3 6.2.12, moox_core 0.9.56, vhs 2.2.0, fluidpages 3.2.0, fluidcontent 4.2.0, flux 7.2.0, fluid 6.2.0.
When you try to create a page in backend - "Fatal error: Declaration of DCNGmbH\MooxCore\Provider\CoreContentProvider::postProcessRecord() must be compatible with FluidTYPO3\Flux\Provider\ProviderInterface::postProcessRecord($operation, $id, array &$row, TYPO3\CMS\Core\DataHandling\DataHandler $reference, array $removals = Array) in /htdocs/domain/typo3conf/ext/moox_core/Classes/Provider/CoreContentProvider.php on line 46"

**Comment by papckoff** [comment]
Thank you! Version 0.9.61 - works fine.
Where can get extensions moox_content_builder and moox_template_builder?

**Comment by adrolli** [comment]
Great to hear, thanks :-D

Both extensions are available here, on Github:
https://github.com/dcngmbh/moox_content_builder
https://github.com/dcngmbh/moox_template_builder

**Comment by papckoff** [comment]
Thanks!

**Comment by papckoff** [comment]
TYPO3 6.2.12 - flux  7.1.2 - vhs 2.2.0 - fluidcontent 4.1.1 - fluidpages 3.1.2 - moox_core - 0.9.61
Fe-templates work fine. Bootstrap – elements It does not appear in the content.
I did the update - flux  7.2.0 - vhs 2.3.1 - fluidcontent 4.2.0 - fluidpages 3.2.0 - Did not help.
P.S. Not true display be-layouts.

**Comment by adrolli** [comment]
A "clear all caches" with Install Tool will fix that.

**Comment by papckoff** [comment]
"A "clear all caches" with Install Tool will fix that." - It does not help(

**Comment by adrolli** [comment]
Checked it on our test-system: 6.2.12, VHS 2.3.2, Flux 7.2.0, fluidcontent 4.2.1 and fluidpages 3.2.2 (should all be latest TER-Versions) with moox_core 0.9.61 and Template Bootstrap 0.9.52 works fine. I've tested all BE and FE features and moox_news. Not tested moox_creative but should run too. You are some versions behind, is it possible to update to the latest versions?

**Comment by papckoff** [comment]
I use TYPO3 6.2.12, VHS 2.3.0, Flux 7.2.0, fluidcontent 4.2.1 and fluidpages 3.2.2 and moox_core 0.9.61. Also MOOX Template Silver 0.9.11. When using the VHS 2.3.2, write error "Could not analyse class: Tx_Flux_ViewHelpers_FlexformViewHelper maybe not loaded or no autoloader?". 
When using moox_creative_0.9.6 write error "Asset "../typo3conf/ext/moox_creative/Resources/Public/Javascript/moox-template.min.js" does not exist.".

**Comment by adrolli** [comment]
Tested Template Silver on our plattform, works fine. Problem seems to be in moox_creative but needs 
 some testing before we are able to publish an update. Is your platform working, if creative is not installed?

**Comment by papckoff** [comment]
Hello. Reinstall site. 6.2.12, VHS 2.3.2, Flux 7.2.0, fluidcontent 4.2.1 and fluidpages 3.2.2, moox_core 0.9.61 and moox_template_free002 0.9.11. It did not help.
![screen1](https://cloud.githubusercontent.com/assets/12158717/7477979/33e5f26e-f360-11e4-8f8d-48a1677a9d1d.jpg)
![screen2](https://cloud.githubusercontent.com/assets/12158717/7477985/3a64e654-f360-11e4-9671-401bec3f1609.jpg)
![screen3](https://cloud.githubusercontent.com/assets/12158717/7477992/3ef7c394-f360-11e4-8f42-cf78db3136d0.jpg)

**Comment by papckoff** [comment]
Helped on / off moox_core in the extension manager. Everything is fine. Thanks for expansion!
