### ISSUE TITLE
Ressourcen über https

### ISSUE THREAD

**Issue by HamburgerJungeJr** [dcngmbh/moox_core#39]
Ich benutze auf einer Seite das SSL-Zertifikat von Cloudflare. Das funktioniert auch alles gut, nur die favicons werden noch über http (mit absolutem Pfad) und nicht über https geladen. Wie kann ich das verändern? Ich konnte keine Konstante, wie in der Doku beschrieben finden.

**Comment by adrolli** [comment]
Moin, ich habe das mal in Resources\Private\Partials\PageObjects.html geändert. Kannst Du das bitte mal testen? 

Entweder den moox_core aus Github aktualisieren oder einfach diese Datei überschreiben, danach Caches leeren.

Thx, Alf

**Comment by HamburgerJungeJr** [comment]
Bei mir verändert sich nichts, wenn ich die Datei ändere.
Ich habe zum testen mal  die Zeile
<v:page.header.link rel="apple-touch-icon" additionalAttributes="{sizes: '57x57'}" href="{settings.extKey}/Favicons/apple-touch-icon-57x57.png" />
geändert, auf der Website hat sich aber nichts geändert.
<link sizes="57x57" rel="apple-touch-icon" href="http://****/fileadmin/moox_template_free002/Favicons/apple-touch-icon-57x57.png"/>
Ich habe alle Caches (auch im Install-Tool) gelöscht.

**Comment by jakub-czyz** [comment]
Verwendest du eine ältere Version von moox_core? Weil eigentlich sollte die aktuellste Version von moox_core das Protokoll "https://" automatisch ohne jegliche Anpassungen unterstützen und bei den Favicons steht kein festes "http://" Protokoll, sondern nur "//".

**Comment by HamburgerJungeJr** [comment]
Ich verwende moox_core 0.9.56
Als base ist auch https angegeben.

**Comment by adrolli** [comment]
@jakub-czyz 
Ich hatte das in den PageObjects geändert, weil noch http bei allen Fav/App-Icons davor war. Hab ich was übersehen?

@HamburgerJungeJr
Kannst Du ohne Cloudflare mit https testen oder uns einen Link zur Seite schicken (moox@dcn.de)?

**Comment by jakub-czyz** [comment]
So wie ich das sehe, hast du in den PageObjects von moox_core einmal google site verification entfernt und irgendwas in der Navigation. Also das sollte wieder rückgängig gemacht werden.

Aber mir ist gerade eingefallen, dass die favicons nicht aus moox_core PageObjects bezogen werden, sondern aus der template extension (https://github.com/dcngmbh/moox_template_free002/blob/master/Resources/Private/Partials/MooxPageHead.html).

@HamburgerJungeJr 
Kann es sein dass du das alte Silver Template verwendest? Mit dem aktuellem Silver Template sollte das funktionieren.

**Comment by HamburgerJungeJr** [comment]
Ja ich verwende das alte SilverTemplate, da mir beim letzten Update einige Desingteile nicht mehr gefielen. Aber dann muss ich wohl das Update machen und das Design wieder anpassen.

**Comment by jakub-czyz** [comment]
Musst du nicht unbedingt.
Gehe mal bei dir in die Datei "typo3conf/ext/moox_template_free002/Resources/Private/Partials/MooxPageObjects.html" und ersetze überall "http://" mit einem Doppel-Slash "//" .... danach sollte dein Problem auch behoben sein.

**Comment by adrolli** [comment]
Ah ... Stirnklatsch, danke Jakub. Habs rückgängig gemacht.
