### ISSUE TITLE
Cookie box button text can't be changed 

### ISSUE THREAD

**Issue by philbaxter** [dcngmbh/moox_core#41]
While the text in the cookie box can be set from the MOOX_CORE_COOKIES constants, there is no mechanism for setting the text on the buttons in the box, these, like the message, are German by default.

**Comment by adrolli** [comment]
Ough, you're right. We will add translation support in constants until next week.

**Comment by philbaxter** [comment]
awesome, thanks

**Comment by adrolli** [comment]
Thanks for your issue Phil. We added constants to moox_core, all templates and template_builder to change the button-text.

**Comment by philbaxter** [comment]
Many thanks, I will give it a try when I get time later this week.
