### ISSUE TITLE
flux:form.section inside another flux:form.section not rendering flux:form.object Properly

### ISSUE THREAD

**Issue by vijayrami** [dcngmbh/moox_core#44]
I can confirm this on dcngmbh/moox_core for Split Button with DropDown FCE (Fluid Content Element) in which its display result in backend like this.

http://screencast.com/t/wIeYk8AUmGl

http://screencast.com/t/QLqnSmpy

I also posted in stackoverflow

http://stackoverflow.com/questions/31242330/fluxform-section-inside-another-fluxform-section-not-rendering-fluxform-objec

**Comment by jakub-czyz** [comment]
Thanks @vijayrami. This issue is adressed in FluidTYPO3/flux#835, means this will be fixed with next Flux version.
