### ISSUE TITLE
flexisel 0.9.9 misses jQuery

### ISSUE THREAD

**Issue by Make66** [dcngmbh/moox_core#45]
when implementing a moox_flexisel on a fresh installation of T3 6.2 with mood silver template, the following errors appear in the console:
Uncaught ReferenceError: jQuery is not defined
in vhs-assets:342

Hint: is the sequence of included JS-libs in the foot correct?
Reference: http://www.taketool.net/index.php?id=1

**Comment by jakub-czyz** [comment]
Can you test it with the current version of moox_core and moox_flexisel from github? I think, this is now solved.

**Comment by Make66** [comment]
Hi Jakub,

thank you for your quick answer!

I did clone 
- moox_clone
- moox_flexisel
- moox template_free002
and cleared all caches

I did see the change on the constant:

plugin.tx_mooxcore.settings.jqueryMovable = 0

No, the wrong sequence of a) vhs-assets b) init for flexisel c) jquery is still there.

With changing the constant jqueryMovable = 1, a) and b) disappeared from the source code, and yes - query is now top of the list! (???)

What else can I try? Do you want an admin?
I would send credentials to your PM

Mit freundlichen Gr��en,

Martin Keller
Taketool GmbH
+49-171-2920432



Am 09.09.2015 um 16:05 schrieb Jakub Czyz <notifications@github.com>:

**Comment by jakub-czyz** [comment]
Hi Make66,

you can send me the credentials at jc@dcn.de. I think this problem is now with your flexisel fce settings.
