### ISSUE TITLE
moox_template_silver page drops font error

### ISSUE THREAD

**Issue by Make66** [dcngmbh/moox_core#46]
On a freshly created and empty page the following bug message appears on the console:

Navigated to http://www.taketool.net/vertical.html
vertical.html:1 Font from origin 'http://maxcdn.bootstrapcdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.taketool.net' is therefore not allowed access. The response had HTTP status code 403.

**Comment by jakub-czyz** [comment]
The issue should be resolved with the latest version from github.
