### ISSUE TITLE
backend.css 404 Not Found

### ISSUE THREAD

**Issue by Make66** [dcngmbh/moox_core#48]
See this in T3 6.2 backend, indicated by FireBug:

"NetworkError: 404 Not Found - http://www.domain.com/typo3/sysext/cms/typo3conf/ext/moox_core/Resources/Public/Stylesheets/backend.css"

called by
http://www.domain.com/typo3/sysext/cms/typo3conf/ext/moox_core/Resources/Public/Stylesheets/backend.css

**Comment by jakub-czyz** [comment]
This issue is resolved with the latest version of moox_core.
