### ISSUE TITLE
Improve sitetitle-adjustments

### ISSUE THREAD

**Issue by adrolli** [dcngmbh/moox_core#54]
Sitetitle is not and adjustable to your own wanted style (e.g. delimiter between sitetitle and pagetitle). Following possibilities:

- TS constants (as for now, multilang-problem)
- Marker in TS sitetitle field (also multilang-prob)
- Root pagetitle (not adjustable but multilang)

**Comment by jakub-czyz** [comment]
can be adjusted in custom templates meta partial
