### ISSUE TITLE
Autoloader

### ISSUE THREAD

**Issue by adrolli** [dcngmbh/moox_core#57]
autoload static templates and how to set "Fluidpages" BE-Layout and the Page-layout to a default one. simplifies the fresh installation of MOOX without pagetree (get an output hassle-free).

Autoload order:

- Fremdextensions
- MOOX Core
- MOOX Extensions
- MOOX Elements
- MOOX Extender
- MOOX Template
- MOOX Custom

**Comment by jakub-czyz** [comment]
Autoload is not possible, following manual order of static templates is mandantory and should be documented.

- Fremdextensions
- MOOX Extensions
- MOOX Elements
- MOOX Extender
- MOOX Core
- MOOX Template
- MOOX Custom
