### ISSUE TITLE
Changes of Constants could not be saved

### ISSUE THREAD

**Issue by CStoerte** [dcngmbh/moox_core#62]
If you install moox 1.0 with git clone together with Typo3 7.6.2 you are not able to save any changes you made in constant editor.
At the moment to workaround define the constants direkt by eding the template, this will help.

**Comment by adrolli** [comment]
Must be a TYPO3 issue or there are multiple Static Templates included, what means they overwrite themselves hierarchically. Are you not able to save your constants or are they saved into the constants field but without effekt?
