### ISSUE TITLE
external links not respecting target

### ISSUE THREAD

**Issue by Make66** [dcngmbh/moox_core#65]
moox_template_free017/Resources/Private/Partials/MooxSuperfishNavigation.html

you need code like this to make external links work with target (adopt 3 x, once for each level)
(Insert as else block after line 31)

`                <f:if condition="{page0.target}!=''">
                  <f:then>
                    <f:link.external uri="{page0.url}" class="{page0.class} item{f:if(condition: subIteration.isFirst, then: 'first-child')} {f:if(condition: subIteration.isLast, then: 'last-child')}" target="{page0.target}">
                      {f:if(condition: page0.nav_title, then: page0.nav_title, else: page0.title)} <i class="glyphicon glyphicon-chevron-right pull-right"></i>
                    </f:link.external>
                  </f:then>
                  <f:else>
                    <f:link.page pageUid="{page0.uid}" class="{page0.class} dropdown-toggle" pageType="{f:if(condition: settings.pagetype, then: settings.pagetype)}">
                      {f:if(condition: page0.nav_title, then: page0.nav_title, else: page0.title)}
                    </f:link.page>
                  </f:else>
                </f:if>
`

**Comment by jakub-czyz** [comment]
fixed in next update
